services:
  app:
    build: .

  db:
    build: db/.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: world
      MYSQL_ROOT_HOST: "%"
    ports:
      - "33060:3306"
